//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e1d4b1f5-cb18-4f65-87cd-93ec4bf5e6e3"",
            ""actions"": [
                {
                    ""name"": ""Paina"",
                    ""type"": ""Button"",
                    ""id"": ""8249d491-dfbe-48ce-8318-c7e374092e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HiirenLiike"",
                    ""type"": ""Value"",
                    ""id"": ""ea3affc9-b4ab-4771-83b4-ef338f1513db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PickDream"",
                    ""type"": ""Button"",
                    ""id"": ""be1da607-319a-46a7-86cf-7617b7edebfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseOver"",
                    ""type"": ""Button"",
                    ""id"": ""f638f178-f70c-4819-893c-6800e2b85380"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8ccd1940-d620-4d7e-b999-2b1753a1e51e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paina"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26c03186-81d4-4c7b-b9a5-15639c694658"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HiirenLiike"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e11c89-4d66-476d-a22f-0ff409a11857"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickDream"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c4dbeec-4de1-4553-ab40-1d6200274ab8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseOver"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Paina = m_Player.FindAction("Paina", throwIfNotFound: true);
        m_Player_HiirenLiike = m_Player.FindAction("HiirenLiike", throwIfNotFound: true);
        m_Player_PickDream = m_Player.FindAction("PickDream", throwIfNotFound: true);
        m_Player_MouseOver = m_Player.FindAction("MouseOver", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Paina;
    private readonly InputAction m_Player_HiirenLiike;
    private readonly InputAction m_Player_PickDream;
    private readonly InputAction m_Player_MouseOver;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Paina => m_Wrapper.m_Player_Paina;
        public InputAction @HiirenLiike => m_Wrapper.m_Player_HiirenLiike;
        public InputAction @PickDream => m_Wrapper.m_Player_PickDream;
        public InputAction @MouseOver => m_Wrapper.m_Player_MouseOver;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Paina.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPaina;
                @Paina.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPaina;
                @Paina.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPaina;
                @HiirenLiike.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHiirenLiike;
                @HiirenLiike.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHiirenLiike;
                @HiirenLiike.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHiirenLiike;
                @PickDream.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickDream;
                @PickDream.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickDream;
                @PickDream.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickDream;
                @MouseOver.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseOver;
                @MouseOver.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseOver;
                @MouseOver.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseOver;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Paina.started += instance.OnPaina;
                @Paina.performed += instance.OnPaina;
                @Paina.canceled += instance.OnPaina;
                @HiirenLiike.started += instance.OnHiirenLiike;
                @HiirenLiike.performed += instance.OnHiirenLiike;
                @HiirenLiike.canceled += instance.OnHiirenLiike;
                @PickDream.started += instance.OnPickDream;
                @PickDream.performed += instance.OnPickDream;
                @PickDream.canceled += instance.OnPickDream;
                @MouseOver.started += instance.OnMouseOver;
                @MouseOver.performed += instance.OnMouseOver;
                @MouseOver.canceled += instance.OnMouseOver;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnPaina(InputAction.CallbackContext context);
        void OnHiirenLiike(InputAction.CallbackContext context);
        void OnPickDream(InputAction.CallbackContext context);
        void OnMouseOver(InputAction.CallbackContext context);
    }
}
